spring:
  datasource:
    url: ${MYSQL_HOST}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
discord:
  authToken: ${DISCORD_AUTH_TOKEN}
  guildId: ${DISCORD_GUILD_ID}
  minimum-daily-reward: 25
  maximum-daily-reward: 100
  minimum-work-reward: 25
  maximum-work-reward: 100
  reward-multiplier: 1
  streak-multiplier: 1.1
  user-list-page-size: 8
  max-game-bet-amount: 300
  command-definitions:
    balance:
      description: "🪙 /balance [user] - Displays the users current Balance, Job and Daily Income"
      options:
        user: "Displays Balance of the specified user"
    daily:
      description: "Gives daily Income"
    richest:
      description: "Shows Richest Leaderboard"
      options:
        page: "Leaderboard Page"
    work:
      description: "Lets you do work hourly!"
    dice:
      description: "Throw two dice and try to make more than your opponent to gain your bet."
      options:
        bet: "How much you want to bet"
    rps:
      description: "Rock paper scissors game"
      options:
        bet: "Bet amount"
        choice: "Rock, paper or scissors"
    roulette:
      description: "Play roulette from your cozy home"
      options:
        bet: "How much do you want to bet?"
    buy:
      description: "Buys an Item"
      options:
        item: "The name of the Shop Item to buy"
        amount: "The amount of items you want to buy (default: 1)"
    give-coins:
      description: "Create coins from the void and give them to someone"
      options:
        user: "The coin receiving user"
        amount: "Amount of coins to give"
      roleRestricted: true
      allowedRoles:
        - 923652378803187802
    gift:
      description: "Gifts an item from the void to a user"
      options:
        user: "The User to give the item to"
        item: "Name of the item to give away"
        amount: "The amount of items to give away (default: 1)"
      roleRestricted: true
      allowedRoles:
        - 923652378803187802
    remove-item:
      description: "Removes an item from a users inventory"
      options:
        user: "The User"
        item: "Name of the item to remove"
        amount: "The amount of items to remove (default: 1)"
      roleRestricted: true
      allowedRoles:
        - 923652378803187802
    give:
      description: "Gives an item from your inventory to another user"
      options:
        user: "The User to give the item to"
        item: "Name of the item to give away"
        amount: "The amount of items to give away (default: 1)"      
    inventory:
      description: "Displays your Inventory"
      options:
        user: "Take a look in this users pockets"
    use:
      description: "Use a item"
      options:
        item: "The item to use"
        amount: "The amount of items to use (default: 1)"
    shop:
      description: "Displays all buyable Items from the Shop"
      options:
        page: "Shop-Page"
    votecampaign:
      description: "Allows management of voting campaigns"
      options:
        create: "Creates a new VoteCampaign"
        addchoice: "Adds a voteable choice to a VoteCampaign"      
        removechoice: "Removes a choice from a VoteCampaign"
        start: "Starts a VoteCampaign"
        stop: "Stops a VoteCampaign"
        list: "Lists all Vote Campaigns"
        name: "Name for VoteCampaign"
        description: "Description for the VoteCampaign"
        campaign: "The campaign"
        choice: "A vote choice"
        page: "VoteCampaign list page"
      roleRestricted: true
      allowedRoles:
        - 923652378803187802
    vote:
      description: "Make your opinion known via a Vote"
    revealvote:
      description: "Reveals a VoteCampaigns Result"
      options:
        campaign: "The VoteCampaign"
      roleRestricted: true
      allowedRoles:
        - 923652378803187802
    clearpendinggames:
      description: "Clears all pending games after a bot restart (debug command)"
      roleRestricted: true
      allowedRoles:
        - 923652378803187802
    chatsummary: 
      description: "Lists the number of messages of every User in the past x hours in a specific channel"
      roleRestricted: true
      allowedRoles:
        - 923652378803187802
      options:
        channel: "Which channel should be summarised?"
        hours: "How many hours back should be summarised?"
        startmessageid: "Id of last message to count"
messages:
  BALANCE_COMMAND_MESSAGE: "%(user) has %(balance)"
  DAILY_COMMAND_MESSAGE: "%(userMention) got %(claimReward) as a daily reward!"
  DAILY_COMMAND_MESSAGE_STREAK: "Congrats for %(claimStreak) days! %(userMention) got %(claimReward) as a daily reward!"
  DAILY_COMMAND_ALREADY_CLAIMED_MESSAGE: "%(userMention) you can't claim more than once per day. You need to wait for %(cooldownHours) hours, %(cooldownMinutes) minutes and %(cooldownSeconds) seconds to claim again."
  WORK_COMMAND_MESSAGE: "%(userMention) worked and got %(claimReward) as reward!"
  WORK_COMMAND_ALREADY_CLAIMED_MESSAGE: "%(userMention) you can't work more than once per hour. You need to wait for %(cooldownMinutes) minutes and %(cooldownSeconds) seconds to work again."
  SHOP_COMMAND_WRONG_PAGE: "%(userMention) you tried to access a non existing shop page!"
  SHOP_TITLE_MESSAGE: "Shop Page %(shopPage)"
  SHOP_HEADER: "Use /buy <item name> to buy an item"
  SHOP_FOOTER: ""
  SHOP_ITEM_DESCRIPTION: "%(shopItemId) - %(itemName) - %(shopItemPrice) - Available: %(shopItemAvailableAmount)\n----%(itemDescription) : /buy %(shopItemBuyName)"
  ITEM_USE_ACTION_UNDEFINED: "%(userMention), this item has no usage action defined. This is likely a configuration error. Please contact an administrator!"
  ITEM_NOT_EXISTS: "%(userMention), the item '%(itemName)' does not exist"
  ITEM_USE_NOT_OWNED: "%(userMention), you don't have %(itemAmount) of this item"
  ITEM_USE_ONLY_SINGLE_ITEM: "%(userMention), the item '%(itemName)' can only be used seperately" 
  ITEM_GIVE_NOT_ENOUGH_OWNED: "%(userMention), you don't have %(itemAmount) of %(itemName) to give away"
  ITEM_GIVE_SUCCESS: "%(userMention), you gave %(receivingUserMention) %(itemAmount) x %(itemName)"
  BUY_ITEM_NO_SUPPLY: "%(userMention), this item has no supply left"
  BUY_ITEM_NOT_ENOUGH_MONEY: "%(userMention), you need to have %(shopItemPrice), but you only have %(balance)"
  BUY_ITEM_SUCCESS: "%(userMention), you bought %(itemAmount)x '%(itemName)'"
  INVENTORY_ITEM_DESCRIPTION: "%(itemAmount)x %(itemName)"
  INVENTORY_ITEM_DESCRIPTION_WITH_USE: "%(itemAmount)x %(itemName) - /use %(itemUseName)"
  INVENTORY_DISPLAY: "Inventory\n%(inventoryBody)"
  ERROR_MESSAGE: "%(errorMessage)\nPlease contact an Administrator!"
  ROLE_REWARD_ALREADY_CLAIMED: "%(userMention), you already have the role '%(role)'"
  ROLE_REWARD_CLAIMED: "%(userMention), you successfully claimed the role '%(role)'"
  RICHEST_COMMAND: "BLANK_HUMANITY Richest Players\n%(richestCommandBody)"
  RICHEST_COMMAND_ENTRY: "%(leaderboardPlace) %(user)\n%(balance)"
  VOTE_CAMPAIGN_CREATED: "VoteCampaign '%(voteCampaignName)' was created"
  VOTE_CAMPAIGN_EXISTS_ALREADY: "A VoteCampaign already exists with the name '%(voteCampaignName)'"
  VOTE_CAMPAIGN_CHOICE_ADDED: "The choice '%(voteChoice)' has been added to the campaign '%(voteCampaignName)'"
  VOTE_CAMPAIGN_NOT_FOUND: "No VoteCampaign exists with the name '%(voteCampaignName)'"
  VOTE_CAMPAIGN_STARTED: "The VoteCampaign '%(voteCampaignName)' was started"
  VOTE_CAMPAIGN_STOPPED: "The VoteCampaign '%(voteCampaignName)' was stopped"
  VOTE_CAMPAIGN_CHOICE_REMOVED: "The choice '%(voteChoice)' was removed from '%(voteCampaignName)'"
  VOTE_CAMPAIGN_CHOICE_NOT_FOUND: "The VoteCampaign '%(voteCampaignName)' has no choice '%(voteChoice)'"
  VOTE_CAMPAIGN_VOTE_DISPLAY_HEADER: "Results of '%(voteCampaignName)'\n - %(voteCampaignDescription) -\n%(voteCampaignVoteChoiceDisplay)"
  VOTE_CAMPAIGN_VOTE_CHOICE_DISPLAY: "  '%(voteChoice)': %(voteCount) votes"
  VOTE_COMMAND_ALREADY_VOTED: "%(userMention), you already voted on this"
  VOTE_COMMAND_VOTED: "%(userMention), you successfully voted for '%(voteChoice)'"
  VOTE_CAMPAIGN_LIST: "VoteCampaign List\n%(voteCampaignListBody)"
  VOTE_CAMPAIGN_LIST_DESCRIPTION: " - %(voteCampaignName)"
  GAME_ON_COOLDOWN: ":no_entry_sign: You need to wait %(cooldownMinutes) minutes and %(cooldownSeconds) seconds to use this command"
  ROCK_PAPER_SCISSORS_TIE: ":dove:\nYou and your opponent both played %(rpsUser)\nYou got your %(betAmount) back"
  ROCK_PAPER_SCISSORS_WIN: "You played %(rpsUser) against %(rpsBot)\nYou won an additional %(betAmount)"
  ROCK_PAPER_SCISSORS_LOSS: "You played %(rpsUser) against %(rpsBot)\nYou lost your %(betAmount)"
  GAME_BET_NOT_ENOUGH_MONEY: "You only have %(balance), but you wanted to bet %(betAmount)!"
  ROULETTE_GAME_RUNNING: "You already have a game running. Please use the reactions to interact with it!"
  ROULETTE_BET_AND_PULL: ":persevere::gun: %(userMention) bets %(betAmount) 🔳 and pulls the trigger..."
  ROULETTE_WIN_MESSAGE: ":hot_face: %(userMention) wins back %(rewardAmount) 🔳"
  ROULETTE_LOSE_MESSAGE: ":skull_crossbones: %(userMention) loses %(betAmount) 🔳"
  ROULETTE_DISPLAY: "%(rouletteHeader)\n%(rouletteResult)"
  DICE_GAME_LOSS: |-
    :game_die: %(user) bets %(betAmount) 🔳 and throws their dice...
    :game_die: %(user) gets %(diceRollUser) ...
    :game_die: %(user), your opponent throws their dice... and gets %(diceRollOpponent)...
    :game_die: %(user), you lost %(betAmount) 🔳
  DICE_GAME_WIN:  |-
    :game_die: %(user) bets %(betAmount) 🔳 and throws their dice...
    :game_die: %(user) gets %(diceRollUser) ...
    :game_die: %(user), your opponent throws their dice... and gets %(diceRollOpponent)...
    :game_die: %(user), you win %(rewardAmount) 🔳
  DICE_GAME_JACKPOT: |-
    :game_die: %(user) bets %(betAmount) 🔳 and throws their dice...
    :game_die: %(user) gets %(diceRollUser) ...
    :game_die: %(user), your opponent throws their dice... and gets %(diceRollOpponent)...
    :game_die: %(user), you rolled a snake eyes and win the jackpot of %(rewardAmount) 🔳
  GIVE_COINS_COMMAND: "%(userMention) has been given %(rewardAmount) 🔳"
  CHAT_SUMMARY_LIST: |-
    Chat Summary for %(channelMention) - Page %(page)
    %(pendingMarker)
    %(chatSummaryBody)
  CHAT_SUMMARY_ENTRY: "%(user): %(messageCount) messages"
  CHAT_SUMMARY_PENDING: "Messages are still counted, please wait!"
  ITEM_REMOVE_SUCCESS: "You have removed %(itemAmount) x %(itemName) from %(user)'s inventory"
items:
  definitions:
    -
      id: 1
      name: "First Class Ticket"
      description: "Useful for you"
      useName: "firstClassTicket"
      action: "ROLE_REWARD"
      actionArguments:
        roleId: 923197747153223700
    -
      id: 2
      name: "High Roller Role"
      description: "Why is this more expensive?"
      useName: "highRollerRole"
      action: "ROLE_REWARD"
      actionArguments:
        roleId: 923652378803187802
    - 
      id: 3
      name: "Kingpin"
      description: "Become the Kingpin"
    - 
      id: 4
      name: ".1 ETH"
      description: "Redeemable for 0.1 ETH after Bitizen Mint"
    - 
      id: 5
      name: ".2 ETH"
      description: "Redeemable for 0.2 ETH after Bitizen Mint"   
shop:
  itemsPerPage: 8
  shopItems:
    -
     id: 1
     itemId: 1
     buyName: "firstClassTicket"
     price: 50
     amountAvailable: 100
    -
     id: 2
     itemId: 2
     buyName: "highRollerRole"
     price: 100
     amountAvailable: 5
    -
     id: 3
     itemId: 3
     buyName: "kingpin"
     price: 200
     amountAvailable: 1
    -
     id: 4
     itemId: 4
     buyName: "pointOneEth"
     price: 1000
     amountAvailable: 1
    -
     id: 5
     itemId: 5
     buyName: "pointTwoEth"
     price: 2000
     amountAvailable: 1
