spring:
  datasource:
    url: ${MYSQL_HOST}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
discord:
  authToken: ${DISCORD_AUTH_TOKEN}
  guildId: ${DISCORD_GUILD_ID}
  minimum-daily-reward: 25
  maximum-daily-reward: 100
  minimum-work-reward: 25
  maximum-work-reward: 100
  reward-multiplier: 1
  streak-multiplier: 1.1
  user-list-page-size: 8
  max-game-bet-amount: 300
  command-definitions:
    balance:
      description: "🪙 /balance [user] - Displays the user's current HC balance."
      options:
        user: "Displays HC balance of the specified user"
    daily:
      description: "Gives daily HC income."
    richest:
      description: "Shows Richest Leaderboard"
      options:
        page: "Leaderboard Page"
    work:
      description: "Lets you do work hourly! Humans love work!"
    dice:
      description: "Throw two dice and try to land a higher number than your opponent!"
      options:
        bet: "How much do you want to bet?"
    rps:
      description: "A classic game of Rock Paper Scissors!"
      options:
        bet: "How much do you want to bet?"
        choice: "Rock, paper or scissors"
    roulette:
      description: "Play roulette with a faulty socket! Can you charge up or will you get shocked and blow a fuse?"
      options:
        bet: "How much do you want to bet?"
    buy:
      description: "Buys an item"
      options:
        item: "The name of the Shop item to buy"
        amount: "The amount of items you want to buy (default: 1)"
    funbuy:
      description: "Buys an item from the Fun Place Shop"
      options:
        item: "The name of the shop item to buy"
        amount: "The amount of items you want to buy (default: 1)"
      roleRestricted: true
      allowedRoles:
        - 881733150923964456 # @Creator
        - 881731045744082964 # @BLANK's Intern
        - 927843505202679878 # @Bitty
    give-coins:
      description: "Create coins from the void and give them to someone"
      options:
        user: "The coin receiving user"
        amount: "Amount of coins to give. Use negative number to remove coins."
      roleRestricted: true
      allowedRoles:
        - 881733150923964456 # @Creator
        - 881731045744082964 # @BLANK's Intern
        - 927843505202679878 # @Bitty
    gift:
      description: "Gifts an item from the void to a user"
      options:
        user: "The user to give the item to"
        item: "Name of the item to give away"
        amount: "The amount of items to give away (default: 1)"
      roleRestricted: true
      allowedRoles:
        - 881733150923964456 # @Creator
        - 881731045744082964 # @BLANK's Intern
        - 927843505202679878 # @Bitty
    remove-item:
      description: "Removes an item from a user's inventory"
      options:
        user: "The user"
        item: "Name of the item to remove"
        amount: "The amount of items to remove (default: 1)"
      roleRestricted: true
      allowedRoles:
        - 881733150923964456 # @Creator
        - 881731045744082964 # @BLANK's Intern
        - 927843505202679878 # @Bitty
    give:
      description: "Gives an item from your inventory to another user"
      options:
        user: "The user to give the item to"
        item: "Name of the item to give away"
        amount: "The amount of items to give away (default: 1)"      
    inventory:
      description: "Displays your inventory"
      options:
        user: "Take a look at this user's inventory HUD"
    use:
      description: "Use an item"
      options:
        item: "The item to use"
        amount: "The amount of items to use (default: 1)"
    shop:
      description: "Displays all buyable items from the BLANK_ Humanity Shop"
      options:
        page: "Shop-Page"
    funshop:
      description: "Displays all buyable Items from the Fun Place Shop"
      options:
        page: "Shop-Page"
      roleRestricted: true
      allowedRoles:
        - 881733150923964456 # @Creator
        - 881731045744082964 # @BLANK's Intern
        - 927843505202679878 # @Bitty
    votecampaign:
      description: "Allows creation and management of polls"
      options:
        create: "Creates a new poll"
        addchoice: "Adds a voteable choice to a poll"      
        removechoice: "Removes a choice from a poll"
        start: "Starts a poll"
        stop: "Stops a poll"
        list: "Lists all existing polls"
        name: "Name for poll"
        description: "Description for the poll"
        campaign: "The poll name"
        choice: "A vote choice"
        page: "Poll list page"
      roleRestricted: true
      allowedRoles:
        - 881733150923964456 # @Creator
        - 881731045744082964 # @BLANK's Intern
        - 927843505202679878 # @Bitty
    vote:
      description: "Vote in a poll"
    revealvote:
      description: "Reveals a Poll's Results"
      options:
        campaign: "The name of the poll"
      roleRestricted: true
      allowedRoles:
        - 881733150923964456 # @Creator
        - 881731045744082964 # @BLANK's Intern
        - 927843505202679878 # @Bitty
    clearpendinggames:
      description: "Clears all pending games after a bot restart (debug command)"
      roleRestricted: true
      allowedRoles:
        - 881733150923964456 # @Creator
        - 881731045744082964 # @BLANK's Intern
        - 927843505202679878 # @Bitty
    chatsummary: 
      description: "Lists the number of messages of every user in the past X hours in a specific channel"
      roleRestricted: true
      allowedRoles:
        - 881733150923964456 # @Creator
        - 881731045744082964 # @BLANK's Intern
        - 927843505202679878 # @Bitty
      options:
        channel: "Which channel should be summarised?"
        hours: "How many hours back should be summarised?"
        startmessageid: "ID of last message to count"
messages:
  BALANCE_COMMAND_MESSAGE: "%(user) has %(balance) <:HC:928474815986302997>."
  DAILY_COMMAND_MESSAGE: "%(userMention) got %(claimReward) <:HC:928474815986302997> as a daily reward! Congrats! See you tomorrow!"
  DAILY_COMMAND_MESSAGE_STREAK: "Current streak: %(claimStreak) days! Nice! %(userMention) got %(claimReward) <:HC:928474815986302997> as a daily reward!"
  DAILY_COMMAND_ALREADY_CLAIMED_MESSAGE: "%(userMention) you can't claim more than once per day. You need to wait for %(cooldownHours) hours, %(cooldownMinutes) minutes and %(cooldownSeconds) seconds to claim again."
  WORK_COMMAND_MESSAGE: "%(userMention) worked and got %(claimReward) <:HC:928474815986302997> as reward!"
  WORK_COMMAND_ALREADY_CLAIMED_MESSAGE: "%(userMention) you can't work more than once per hour. You need to wait for %(cooldownMinutes) minutes and %(cooldownSeconds) seconds to work again."
  SHOP_COMMAND_WRONG_PAGE: "%(userMention) you tried to access a nonexistent Shop page!"
  SHOP_TITLE_MESSAGE: "BLANK_ Humanity Shop"
  SHOP_HEADER: "Use /buy <Item ID> to buy an item\n\n:money_with_wings: **Here are our items:**\n"
  SHOP_FOOTER: "Page %(shopPage)"
  FUN_PLACE_SHOP_TITLE_MESSAGE: "The Fun Place Shop"
  FUN_PLACE_SHOP_HEADER: "Use /buy <Item ID> to buy an item\n\n:money_with_wings: **Here are the available Fun Place items:**\n"
  FUN_PLACE_SHOP_FOOTER: "Page %(shopPage)"
  SHOP_ITEM_DESCRIPTION: "**%(itemName) - %(shopItemPrice)** <:HC:928474815986302997>\n%(itemDescription)\nItem ID: ``%(shopItemBuyName)``\n"
  ITEM_USE_ACTION_UNDEFINED: "%(userMention), this item has no usage action defined. This is likely a configuration error. Please contact an administrator!"
  ITEM_NOT_EXISTS: "%(userMention), the item '%(itemName)' does not exist."
  ITEM_USE_NOT_OWNED: "%(userMention), you don't have %(itemAmount) of this item."
  ITEM_USE_ONLY_SINGLE_ITEM: "%(userMention), the item '%(itemName)' can only be used seperately." 
  ITEM_USE_ONLY_REQUIRED_AMOUNT: "%(userMention), the item '%(itemName)' requires the use of exactly '%(itemAmount)'x items."
  ITEM_GIVE_NOT_ENOUGH_OWNED: "%(userMention), you don't have %(itemAmount) of %(itemName) to give away."
  ITEM_GIVE_SUCCESS: "%(userMention), you gave %(receivingUserMention) %(itemAmount) x %(itemName)."
  BUY_ITEM_NO_SUPPLY: "%(userMention), this item has no supply left."
  BUY_ITEM_NOT_ENOUGH_MONEY: "%(userMention) checks their <:HC:928474815986302997> and finds there is not enough to purchase the item they wanted. %(itemName) costs %(shopItemPrice), but they only have %(balance)."
  BUY_ITEM_SUCCESS: "%(userMention), you bought %(itemAmount)x '%(itemName)'"
  INVENTORY_ITEM_DESCRIPTION: "%(itemAmount)x %(itemName)"
  INVENTORY_ITEM_DESCRIPTION_WITH_USE: "%(itemAmount)x %(itemName) - /use %(itemUseName)"
  INVENTORY_DISPLAY: "Inventory\n%(inventoryBody)"
  ERROR_MESSAGE: "%(errorMessage)\nPlease contact an Administrator!"
  ROLE_REWARD_ALREADY_CLAIMED: "%(userMention), you already have the role '%(role)'"
  ROLE_REWARD_CLAIMED: "%(userMention), you successfully claimed the role '%(role)'"
  RICHEST_COMMAND: "<:HC_Bag:928475202843725905> **BLANK_ Humanity's Richest Players** <:HC_Bag:928475202843725905>\n\n%(richestCommandBody)"
  RICHEST_COMMAND_ENTRY: "**%(leaderboardPlace) - %(user)**\n<:HC:928474815986302997> %(balance)\n"
  VOTE_CAMPAIGN_CREATED: "The poll '%(voteCampaignName)' was created"
  VOTE_CAMPAIGN_EXISTS_ALREADY: "A poll already exists with the name '%(voteCampaignName)'"
  VOTE_CAMPAIGN_CHOICE_ADDED: "The choice '%(voteChoice)' has been added to the poll '%(voteCampaignName)'"
  VOTE_CAMPAIGN_NOT_FOUND: "No poll exists with the name '%(voteCampaignName)'"
  VOTE_CAMPAIGN_STARTED: "The poll '%(voteCampaignName)' was started"
  VOTE_CAMPAIGN_STOPPED: "The poll '%(voteCampaignName)' was stopped"
  VOTE_CAMPAIGN_CHOICE_REMOVED: "The choice '%(voteChoice)' was removed from '%(voteCampaignName)'"
  VOTE_CAMPAIGN_CHOICE_NOT_FOUND: "The poll '%(voteCampaignName)' has no choice '%(voteChoice)'"
  VOTE_CAMPAIGN_VOTE_DISPLAY_HEADER: "**Results of '%(voteCampaignName)'**\n - %(voteCampaignDescription) -\n%(voteCampaignVoteChoiceDisplay)"
  VOTE_CAMPAIGN_VOTE_CHOICE_DISPLAY: "'%(voteChoice)': %(voteCount) votes"
  VOTE_COMMAND_ALREADY_VOTED: "%(userMention), you already voted on this."
  VOTE_COMMAND_VOTED: "%(userMention), you successfully voted for '%(voteChoice)'"
  VOTE_CAMPAIGN_LIST: "Poll List\n%(voteCampaignListBody)"
  VOTE_CAMPAIGN_LIST_DESCRIPTION: " - %(voteCampaignName)"
  GAME_ON_COOLDOWN: ":no_entry_sign: You need to wait %(cooldownMinutes) minutes and %(cooldownSeconds) seconds to use this command"
  ROCK_PAPER_SCISSORS_TIE: ":dove:\nYou and your opponent both played %(rpsUser)\nYou got your %(betAmount) <:HC:928474815986302997> back."
  ROCK_PAPER_SCISSORS_WIN: "You played %(rpsUser) against %(rpsBot)\nYou won an additional %(betAmount) <:HC:928474815986302997>."
  ROCK_PAPER_SCISSORS_LOSS: "You played %(rpsUser) against %(rpsBot)\nYou lost your %(betAmount) <:HC:928474815986302997>."
  GAME_BET_NOT_ENOUGH_MONEY: "You wanted to bet %(betAmount) <:HC:928474815986302997>, but you only have %(balance) <:HC:928474815986302997>!"
  ROULETTE_GAME_RUNNING: "You already have a game running. Please use the reactions to interact with it!"
  ROULETTE_BET_AND_PULL: ":pleading_face::confounded: %(userMention) bets %(betAmount) <:HC:928474815986302997> and tries the socket..."
  ROULETTE_WIN_MESSAGE: ":sweat_smile: Success! %(userMention) wins back %(rewardAmount) <:HC:928474815986302997>"
  ROULETTE_LOSE_MESSAGE: ":zap::skull_crossbones::zap: %(userMention) blows a fuse and loses %(betAmount) <:HC:928474815986302997>"
  ROULETTE_DISPLAY: "%(rouletteHeader)\n%(rouletteResult)"
  DICE_GAME_LOSS: |-
    :game_die: %(user) bets %(betAmount) <:HC:928474815986302997> and throws their dice...
    :game_die: %(user) gets %(diceRollUser) ...
    :game_die: %(user), your opponent throws their dice... and gets %(diceRollOpponent)...
    :game_die: %(user), you lost %(betAmount) <:HC:928474815986302997>
  DICE_GAME_WIN:  |-
    :game_die: %(user) bets %(betAmount) <:HC:928474815986302997> and throws their dice...
    :game_die: %(user) gets %(diceRollUser) ...
    :game_die: %(user), your opponent throws their dice... and gets %(diceRollOpponent)...
    :game_die: %(user), you win %(rewardAmount) <:HC:928474815986302997>
  DICE_GAME_JACKPOT: |-
    :game_die: %(user) bets %(betAmount) <:HC:928474815986302997> and throws their dice...
    :game_die: %(user) gets %(diceRollUser) ...
    :game_die: %(user), your opponent throws their dice... and gets %(diceRollOpponent)...
    :game_die: %(user), you rolled a snake eyes and win the jackpot of %(rewardAmount) <:HC:928474815986302997>
  GIVE_COINS_COMMAND: "%(userMention) has been given %(rewardAmount) <:HC:928474815986302997>"
  CHAT_SUMMARY_LIST: |-
    Chat Summary for %(channelMention) - Page %(page)
    %(pendingMarker)
    %(chatSummaryBody)
  CHAT_SUMMARY_ENTRY: "%(user): %(messageCount) messages"
  CHAT_SUMMARY_PENDING: "Messages are still counted, please wait!"
  ITEM_REMOVE_SUCCESS: "You have removed %(itemAmount) x %(itemName) from %(user)'s inventory"
items:
  definitions:
    -
      id: 1
      name: "High Roller Role"
      description: "Do you want to show off your superiority? Humans are competitive creatures, and with this role, you prove you are among the best. 💸"
      useName: "highRollerRole"
      action: "ROLE_REWARD"
      actionArguments:
        roleId: 923462845688074251
    - 
      id: 2
      name: ".1 ETH (1 Available)"
      description: ".1 Ethereum paid directly to your wallet."
    - 
      id: 3
      name: ".2 ETH (1 Available)"
      description: ".2 Ethereum paid directly to your wallet." 
    - 
      id: 4
      name: "Propaganda Token"
      description: "Each Faction Propaganda sticker requires 4 tokens to unlock and resets on Tuesdays. See <#940002641088512050> for details." #Channel ID links to the-cup-shop
      useName: "propagandaToken"
      action: MESSAGE_ACTION
      actionArguments:
        requiredAmount: 4
        replyMessage: "A Propaganda Sticker has been activated by %(user)! The Overseer has been notified!"
        messageSend: "<@&927843505202679878>, a Propaganda Sticker has been activated by %(user)!" #Pings @Bitty
        messageSendChannel: 941462314119462932
    - 
      id: 5
      name: "Faction Emoji Token"
      description: "Each emoji requires 4 tokens to unlock. There are four purchasable emojis per faction. See <#940002641088512050> for details." #Channel ID links to the-cup-shop
      useName: "factionEmojiToken"
      action: MESSAGE_ACTION
      actionArguments:
        requiredAmount: 4
        replyMessage: "A Faction Emoji has been activated by %(user)! The Overseer has been notified!"
        messageSend: "<@&927843505202679878>, a Faction Emoji has been activated by %(user)!" #Pings @Bitty
        messageSendChannel: 941462314119462932
    -
      id: 6
      name: "Valentine (Limited Time Only)"
      description: "Gift these Valentines to your friends or buy one for yourself! Upon /use, this will give the user a temporary Valentine role, which will grant access to a special Valentine POAP!"
      useName: "valentine"
      action: "ROLE_REWARD"
      actionArguments:
        roleId: 942274318988103711
shop:
  itemsPerPage: 8
  shopItems:
    -
     order: 1
     id: 6
     itemId: 6
     buyName: "valentine"
     price: 10
     amountAvailable: -1
    -
     order: 2
     id: 4
     itemId: 4
     buyName: "propagandaToken"
     price: 10000
     amountAvailable: -1
    -
     order: 3
     id: 5
     itemId: 5
     buyName: "factionEmojiToken"
     price: 50000
     amountAvailable: -1
    -
     order: 4
     id: 1
     itemId: 1
     buyName: "highRollerRole"
     price: 100000
     amountAvailable: -1
    -
     order: 5
     id: 2
     itemId: 2
     buyName: "pointOneEth"
     price: 750000
     amountAvailable: 1
    -
     order: 6
     id: 3
     itemId: 3
     buyName: "pointTwoEth"
     price: 999999
     amountAvailable: 1
funshop:  # Different Shop, uses different IDs
  itemsPerPage: 8
  shopItems: []
