name: Deploy Configuration

on:
  workflow_run:
    workflows: ["Validate application.yml"]
    branches: ["main"]
    types: ["completed"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.SERVER }}
        FTP_USERNAME: ${{ secrets.USERNAME }}
        FTP_PASSWORD: ${{ secrets.PASSWORD }}
        LOCAL_DIR: ./config/
        REMOTE_DIR: /root/BlankDiscordBot/config/
        METHOD: sftp
        PORT: 22
        ARGS: --verbose
