name: Validate application.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: InoUno/yaml-ls-check@v1.1.0
      with:
        schemaMapping: |
          {
            "https://raw.githubusercontent.com/BLANKHumanity/blank-humanity-discord-bot/main/blankdiscordbot-core/src/main/resources/config-schema.json": [ "application.yml" ]
          }

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        ftp_server: ${{ secrets.SERVER }}
        ftp_username: ${{ secrets.USERNAME }}
        ftp_password: ${{ secrets.PASSWORD }}
        local_dir: ./
        server_dir: /BlankDiscordBot/config/
        args: --insecure


