name: Validate application.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: InoUno/yaml-ls-check@v1.1.0
      with:
        schemaMapping: |
          {
            "https://raw.githubusercontent.com/BLANKHumanity/blank-humanity-discord-bot/main/blankdiscordbot-core/src/main/resources/config-schema.json": [ "application.yml" ]
          }

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        ftp-server: ${{ secrets.SERVER }}
        ftp-username: ${{ secrets.USERNAME }}
        ftp-password: ${{ secrets.PASSWORD }}
        local-dir: ./
        server-dir: /BlankDiscordBot/config/
        git-ftp-args: --insecure


